---
title: "Untitled"
output: html_document
---
```{r}
library('dplyr')
```

# Import Datasets
```{r}

Non_Motorists <- read.csv("https://data.montgomerycountymd.gov/api/views/n7fk-dce5/rows.csv?accessType=DOWNLOAD")

```

```{r}
Non_Motorists$Injury.Severity <- recode(Non_Motorists$Injury.Severity,"FATAL INJURY"=5,"SUSPECTED SERIOUS INJURY"=4, "POSSIBLE INJURY"=3,"SUSPECTED MINOR INJURY"=2,"NO APPARENT INJURY"=1)

```

```{r}
Non_Motorists$Weather <- recode(Non_Motorists$Weather,"BLOWING SNOW"=0,"CLEAR"=1,"CLOUDY"=1,"FOGGY"=0,"N/A"=-99,
       "OTHER"=-99,"RAINING"=0,"SEVERE WINDS"=0,"SLEET"=0,"SNOW"=0,"UNKNOWN"=-99,"WINTRY MIX"=0)
Non_Motorists <- Non_Motorists[! Non_Motorists$Weather == -99,]
```

```{r}
Non_Motorists$Light <- recode(Non_Motorists$Light,"DARK -- UNKNOWN LIGHTING"=0,"DARK LIGHTS ON"=0,"DARK NO LIGHTS"=0,
        "DAWN"=1,"DAYLIGHT"=1,"DUSK"=1,"N/A"=-99,"OTHER"=-99,"UNKNOWN"=-99)
Non_Motorists <- Non_Motorists[! Non_Motorists$Light == -99,]
```

```{r}
Non_Motorists$Surface.Condition <- recode(Non_Motorists$Surface.Condition," "=-99,"DRY"=1,"ICE"=0,"N/A"=-99,"OTHER"=-99,"SLUSH"=0,
       "SNOW"=0,"UNKNOW"=-99,"WET"=0)
Non_Motorists <- Non_Motorists[! Non_Motorists$Surface.Condition == -99,]
```

```{r}
Non_Motorists$Traffic.Control <- recode(Non_Motorists$Traffic.Control,"FLASHING TRAFFIC SIGNAL"=1,"N/A"=-99,"NO CONTROLS"=0,
       "OTHER"=-99,"PERSON"=1,"RAILWAY CROSSING DEVICE"=1,"SCHOOL ZONE SIGN DEVICE"=1,
       "STOP SIGN"=1,"TRAFFIC SIGNAL"=1,"UNKNOWN"=-99,"WARNING SIGN"=1,"YIELD SIGN"=1)
Non_Motorists <- Non_Motorists[! Non_Motorists$Traffic.Control == -99,]

```

```{r}
Non_Motorists$At.Fault <- recode(Non_Motorists$At.Fault,"No"=0,"Unknown"=-99,"Yes"=1)
Non_Motorists <- Non_Motorists[! Non_Motorists$At.Fault == -99,]
```

```{r}
Non_Motorists$Crash.Date.Time <- substring(as.character(Non_Motorists$Crash.Date.Time),1,10)
```

```{r}
Non_Motorists_1 <- Non_Motorists%>%select(Crash.Date.Time, Injury.Severity, Weather, Light, Surface.Condition, Traffic.Control,At.Fault)
Non_Motorists_2 <-na.omit(Non_Motorists_1)
```

```{r}
View(Non_Motorists_2)
```











